name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: fevm-owner-actor - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: wget https://github.com/ethereum/solidity/releases/download/v0.8.17/solc-static-linux -o solc
      - run: chmod a+x solc
